#Banco de Dados: *Jobs and Salaries in Data Science*
Fonte: Kaggle - Acesso: https://www.kaggle.com/datasets/hummaamqaasim/jobs-in-data/code?datasetId=4213326&language=Python&outputs=Visualization

#Descrição do Banco de Dados:

Este conjuntos de dados reune informações reais sobre empregos e salarios na área de dados

#Introdução aos conceits de Análise Exploratória

Bibliotecas:
- Python

In [ ]:
# Bibliotecas

import pandas as pd # Dataframe - principal ferramenta para análise de dados
import numpy as np# Operação númerica

import matplotlib.pyplot as plt # Visualização dos Dados

#Passo 1: **Carregando o Banco de Dados**

nesse momento usaremos df. dataframe para nosso banco de dados

In [ ]:
df = pd.read_csv("jobs_in_data.csv")

NameError: name 'pd' is not defined

Perguntas que a analise inicial responde rapidamente com poucos comandos!

- quantas linhas (Observações) e colunas (variaves) o dataset possui;
- quais são os nomes das colunas;
- quais os tipos de dados de cada variavéis;
- se existem valores ausentes de cada variavéis;
- se há indicadores de dados redundantes ou inconsistentes;
- estatísticas básico dos dados númericos.

Estrutura Geral Dataframe: *df.inf()*

Estatística Descritiva *df.describe()*

Visualização das primeiras e últimas linhas: *df.head(n)* e *df.tail(n)*, n a quantidade de observações que eu quero exibir

Obs.: Exibição de Resultado:
- print() - mais simples
- display() - mas estilizado

In [ ]:
print(df.head(10))

   work_year                    job_title                    job_category  \
0       2023         Data DevOps Engineer                Data Engineering
1       2023               Data Architect  Data Architecture and Modeling
2       2023               Data Architect  Data Architecture and Modeling
3       2023               Data Scientist       Data Science and Research
4       2023               Data Scientist       Data Science and Research
5       2023               Data Scientist       Data Science and Research
6       2023               Data Scientist       Data Science and Research
7       2023  Machine Learning Researcher         Machine Learning and AI
8       2023  Machine Learning Researcher         Machine Learning and AI
9       2023                Data Engineer                Data Engineering

  salary_currency  salary  salary_in_usd employee_residence experience_level  \
0             EUR   88000          95012            Germany        Mid-level
1             USD  186000         186000      United States           Senior
2             USD   81800          81800      United States           Senior
3             USD  212000         212000      United States           Senior
4             USD   93300          93300      United States           Senior
5             USD  130000         130000      United States           Senior
6             USD  100000         100000      United States           Senior
7             USD  224400         224400      United States        Mid-level
8             USD  138700         138700      United States        Mid-level
9             USD  210000         210000      United States        Executive

  employment_type work_setting company_location company_size
0       Full-time       Hybrid          Germany            L
1       Full-time    In-person    United States            M
2       Full-time    In-person    United States            M
3       Full-time    In-person    United States            M
4       Full-time    In-person    United States            M
5       Full-time       Remote    United States            M
6       Full-time       Remote    United States            M
7       Full-time    In-person    United States            M
8       Full-time    In-person    United States            M
9       Full-time       Remote    United States            M

In [ ]:
print(df.tail(10))

      work_year                           job_title  \
9345       2020           Machine Learning Engineer
9346       2021            Director of Data Science
9347       2021                      Data Scientist
9348       2021  Applied Machine Learning Scientist
9349       2021                       Data Engineer
9350       2021                     Data Specialist
9351       2020                      Data Scientist
9352       2021            Principal Data Scientist
9353       2020                      Data Scientist
9354       2020               Business Data Analyst

                      job_category salary_currency  salary  salary_in_usd  \
9345       Machine Learning and AI             EUR   40000          45618
9346     Data Science and Research             USD  168000         168000
9347     Data Science and Research             SGD  160000         119059
9348       Machine Learning and AI             USD  423000         423000
9349              Data Engineering             EUR   24000          28369
9350  Data Management and Strategy             USD  165000         165000
9351     Data Science and Research             USD  412000         412000
9352     Data Science and Research             USD  151000         151000
9353     Data Science and Research             USD  105000         105000
9354                 Data Analysis             USD  100000         100000

     employee_residence experience_level employment_type work_setting  \
9345            Croatia           Senior       Full-time       Remote
9346              Japan           Senior       Full-time    In-person
9347          Singapore        Mid-level       Full-time       Remote
9348      United States        Mid-level       Full-time       Hybrid
9349              Malta        Mid-level       Full-time       Hybrid
9350      United States           Senior       Full-time       Remote
9351      United States           Senior       Full-time       Remote
9352      United States        Mid-level       Full-time       Remote
9353      United States      Entry-level       Full-time       Remote
9354      United States      Entry-level        Contract       Remote

     company_location company_size
9345          Croatia            S
9346            Japan            S
9347           Israel            M
9348    United States            L
9349            Malta            L
9350    United States            L
9351    United States            L
9352    United States            L
9353    United States            S
9354    United States            L

In [ ]:
display(df.head(10))

,work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size
0,2023,Data DevOps Engineer,Data Engineering,EUR,88000,95012,Germany,Mid-level,Full-time,Hybrid,Germany,L
1,2023,Data Architect,Data Architecture and Modeling,USD,186000,186000,United States,Senior,Full-time,In-person,United States,M
2,2023,Data Architect,Data Architecture and Modeling,USD,81800,81800,United States,Senior,Full-time,In-person,United States,M
3,2023,Data Scientist,Data Science and Research,USD,212000,212000,United States,Senior,Full-time,In-person,United States,M
4,2023,Data Scientist,Data Science and Research,USD,93300,93300,United States,Senior,Full-time,In-person,United States,M
5,2023,Data Scientist,Data Science and Research,USD,130000,130000,United States,Senior,Full-time,Remote,United States,M
6,2023,Data Scientist,Data Science and Research,USD,100000,100000,United States,Senior,Full-time,Remote,United States,M
7,2023,Machine Learning Researcher,Machine Learning and AI,USD,224400,224400,United States,Mid-level,Full-time,In-person,United States,M
8,2023,Machine Learning Researcher,Machine Learning and AI,USD,138700,138700,United States,Mid-level,Full-time,In-person,United States,M
9,2023,Data Engineer,Data Engineering,USD,210000,210000,United States,Executive,Full-time,Remote,United States,M

In [ ]:
display(df.tail(10))

,work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size
9345,2020,Machine Learning Engineer,Machine Learning and AI,EUR,40000,45618,Croatia,Senior,Full-time,Remote,Croatia,S
9346,2021,Director of Data Science,Data Science and Research,USD,168000,168000,Japan,Senior,Full-time,In-person,Japan,S
9347,2021,Data Scientist,Data Science and Research,SGD,160000,119059,Singapore,Mid-level,Full-time,Remote,Israel,M
9348,2021,Applied Machine Learning Scientist,Machine Learning and AI,USD,423000,423000,United States,Mid-level,Full-time,Hybrid,United States,L
9349,2021,Data Engineer,Data Engineering,EUR,24000,28369,Malta,Mid-level,Full-time,Hybrid,Malta,L
9350,2021,Data Specialist,Data Management and Strategy,USD,165000,165000,United States,Senior,Full-time,Remote,United States,L
9351,2020,Data Scientist,Data Science and Research,USD,412000,412000,United States,Senior,Full-time,Remote,United States,L
9352,2021,Principal Data Scientist,Data Science and Research,USD,151000,151000,United States,Mid-level,Full-time,Remote,United States,L
9353,2020,Data Scientist,Data Science and Research,USD,105000,105000,United States,Entry-level,Full-time,Remote,United States,S
9354,2020,Business Data Analyst,Data Analysis,USD,100000,100000,United States,Entry-level,Contract,Remote,United States,L

#Estrutura Geral do DataFrame

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9355 entries, 0 to 9354
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           9355 non-null   int64
 1   job_title           9355 non-null   object
 2   job_category        9355 non-null   object
 3   salary_currency     9355 non-null   object
 4   salary              9355 non-null   int64
 5   salary_in_usd       9355 non-null   int64
 6   employee_residence  9355 non-null   object
 7   experience_level    9355 non-null   object
 8   employment_type     9355 non-null   object
 9   work_setting        9355 non-null   object
 10  company_location    9355 non-null   object
 11  company_size        9355 non-null   object
dtypes: int64(3), object(9)
memory usage: 877.2+ KB

#Estatísca Discritiva

In [ ]:
df.describe()

         work_year         salary  salary_in_usd
count  9355.000000    9355.000000    9355.000000
mean   2022.760449  149927.981293  150299.495564
std       0.519470   63608.835387   63177.372024
min    2020.000000   14000.000000   15000.000000
25%    2023.000000  105200.000000  105700.000000
50%    2023.000000  143860.000000  143000.000000
75%    2023.000000  187000.000000  186723.000000
max    2023.000000  450000.000000  450000.000000

In [ ]:
from google.colab import drive
drive.mount('/content/drive')